version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./back/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: linus
      POSTGRES_PASSWORD: linus1001
      POSTGRES_DB: linus_db
    networks:
      - app-network

  api:
    build: ./back
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: linus
      POSTGRES_HOST: db
      POSTGRES_DB: linus_db
      POSTGRES_PASSWORD: linus1001
      POSTGRES_PORT: 5432
      PORT: 3000
    depends_on:
      - db
    networks:
      - app-network

  front:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
